FactorioItemBrowser\ExportQueue\Client\Entity\Job:
  access_type: public_method
  exclusion_policy: all
  properties:
    id:
      type: string
    combinationId:
      type: string
    modNames:
      type: array<string>
    priority:
      type: string
    status:
      type: string
    errorMessage:
      type: string
      skip_when_empty: string
    creator:
      type: string
      skip_when_empty: string
    creationTime:
      type: DateTime<'Y-m-d\TH:i:sP', '', 'Y-m-d\TH:i:sP'>
    exporter:
      type: string
      skip_when_empty: string
    exportTime:
      type: DateTime<'Y-m-d\TH:i:sP', '', 'Y-m-d\TH:i:sP'>
    importer:
      type: string
      skip_when_empty: string
    importTime:
      type: DateTime<'Y-m-d\TH:i:sP', '', 'Y-m-d\TH:i:sP'>
