FactorioItemBrowser\ExportQueue\Client\Request\Job\CreateRequest:
  access_type: public_method
  exclusion_policy: all
  properties:
    combinationId:
      type: string
    modNames:
      type: array<string>
