FactorioItemBrowser\ExportQueue\Client\Request\Job\UpdateRequest:
  access_type: public_method
  exclusion_policy: all
  properties:
    status:
      type: string
    errorMessage:
      type: string
